const MATCH_MODES = Object.freeze({
    PVP: "PVP",
    PVE: "PVE",
});

const MATCH_SEARCH_STEP_MS = 10000;
const MATCH_SEARCH_RANGE_STEP = 100;
const FULL_QUEUE_SEARCH_AFTER_MS = 30000;

const FIELD_WIDTH = 15;
const FIELD_HEIGHT = 40;
const TEAM_SPAWN_MARGIN = 4;

module.exports = {
    MATCH_MODES,
    MATCH_SEARCH_STEP_MS,
    MATCH_SEARCH_RANGE_STEP,
    FULL_QUEUE_SEARCH_AFTER_MS,
    FIELD_WIDTH,
    FIELD_HEIGHT,
    TEAM_SPAWN_MARGIN,
};
